### ISSUE TITLE
Samba 4.7+

### ISSUE THREAD

**Issue by metri** [swiftstack/proxyfs-vfs#8]
Hello! Are there any plans to support Samba 4.7+ versions?

**Comment by edmc-ss** [comment]
Definitely @metri - and sorry for not seeing this sooner...
I've mostly been watching only the ProxyFS repo...

Meanwhile, please come join us on the ProxyFS Slack Channel [(Slack Link)...](https://proxyfs.slack.com/) there has been quite a bit of recent discussion about exactly this issue there.
